### ISSUE TITLE
Edit wrong or submit missing lyrics?

### ISSUE THREAD

**Issue by ghost** [emilioastarita/lyricfier#11]
Hey there,

I am pretty new to Spotify and Lyricfier. Where does Lyricfier get the lyrics from and is there any possibility to edit wrong lyrics or submit missing ones?
I hope my question is not too noob.
Thanx in advance

_Tattva_

**Comment by emilioastarita** [comment]
No. You must submit the fixed lyrics to Wikia and/or MusicMatch.  We have scraping plugins for these sites but we don't own the content.

**Comment by rickmills** [comment]
Would it not make sense to link to the source in that case? In the spirit of keeping things open, it seems like it might be considered bad form not to do so.
