### ISSUE TITLE
App size

### ISSUE THREAD

**Issue by RobFog** [emilioastarita/lyricfier#12]
The (Mac) app comes in at a whopping 370MB. Does it also work as a PhotoShop replacement? :-P

In all earnest: How is that possible? Does the app ship with a massive amount of dependencies?

**Comment by emilioastarita** [comment]
Yes it's a lot. We are using electron that basically is browser (chrome) that runs the node app. This cost a lot of mbs but you can target 3 plattaforms very easily.

**Comment by RobFog** [comment]
I see.

I reckon you have considered other options like QT and Mono? I'm not a programmer but as far as I can tell QT works very well in the case of [Musescore](https://github.com/musescore/MuseScore).

**Comment by emilioastarita** [comment]
both mono and qt ecosystems could be good candidates for a desktop app but I'm mainly a web programmer so something as electron is the natural choice in my case. Also it's a lot easier for me to get collaborators involved just as @silvestreh because I have lot of web programmers friends!

**Comment by RobFog** [comment]
Fair enough. :-)
