### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by jacekmiecznikowski** [emilioastarita/lyricfier#14]
It would be great if you could add dark theme matching the spotify color scheme.

**Comment by Madh93** [comment]
Color scheme in [main.css](https://github.com/emilioastarita/lyricfier/blob/master/render/css/main.css):

`.lyrics { background-color: #181818; }`
`:root { color: #fff; }`
`.refresh { color: white; }`
`:hover ::-webkit-scrollbar-thumb { background: #333; }`

![Bye Leonard Cohen](http://oi63.tinypic.com/34rvk3m.jpg)

**Comment by emilioastarita** [comment]
thx for styles! added to master.
