### ISSUE TITLE
Mac tray icons aren't monochrome

### ISSUE THREAD

**Issue by iiiGerardoiii** [emilioastarita/lyricfier#18]
The colorful icon looks weird along the rest of monochrome icons on the menubar.
Something like this would look better imo: ![captura de pantalla 2016-11-21 17 32 43](https://cloud.githubusercontent.com/assets/6264194/20505439/8c245784-b012-11e6-9dba-43cf3fabc051.png)

**Comment by emilioastarita** [comment]
@silvestreh any help here?

**Comment by emilioastarita** [comment]
@iiiGerardoiii do you want to send a pull request with new icons ?

**Comment by iiiGerardoiii** [comment]
@emilioastarita sorry I don't know how to make it switch to its light/dark menubar version automatically, the one I showed is only for dark menubars, if I switch to light menubar it won't be visible.

Here are the icons if anyone wants to implement them properly, feel free to use them:
[lyricfier monochrome menubar icons v2.zip](https://github.com/emilioastarita/lyricfier/files/1358135/lyricfier.monochrome.menubar.icons.v2.zip)

**Comment by emilioastarita** [comment]
ping @silvestreh
