### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by david-brauer** [emilioastarita/lyricfier#21]
It would be nice to have a button to change the font-size. In developer options this already works with e.g. fon-size:25pt, but after closing the programm restores the default font-size.

**Comment by mrkmndz** [comment]
Hey @emilioastarita is this something that we would want in the currently inaccessible Settings view? Perhaps also including an adjuster for refresh time?

**Comment by emilioastarita** [comment]
@mrkmndz yes. That settings page was intended for this kind of adjustment. Also we can add the dark theme switcher there. Do you want to work in this issue?

**Comment by mrkmndz** [comment]
Sure, I should be able to put that along with always on top

**Comment by mrkmndz** [comment]
closed by #34

**Comment by mrkmndz** [comment]
@emilioastarita can you close this?
