### ISSUE TITLE
Problema al tratar de iniciar la app

### ISSUE THREAD

**Issue by kalber** [emilioastarita/lyricfier#22]
Buenas tardes.

Tengo un problema al tratar de iniciar la aplicación después de haber clonado.

El error que me aparece es el siguiente:

npm start

> lyricfier@0.2.2 prestart /Users/desarollo/Documents/proyectos/lyricfier
> tsc && lessc render/less/main.less render/css/main.css

node_modules/@types/electron/index.d.ts(773,30): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(2603,21): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(2813,30): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(3254,24): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(3975,21): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(4436,93): error TS2304: Cannot find name 'Promise'.
node_modules/@types/electron/index.d.ts(5295,93): error TS2304: Cannot find name 'Promise'.
node_modules/@types/electron/index.d.ts(5520,93): error TS2304: Cannot find name 'Promise'.

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! lyricfier@0.2.2 prestart: `tsc && lessc render/less/main.less render/css/main.css`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lyricfier@0.2.2 prestart script 'tsc && lessc render/less/main.less render/css/main.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lyricfier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && lessc render/less/main.less render/css/main.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lyricfier
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lyricfier
npm ERR! There is likely additional logging output above.

Gracias.

**Comment by emilioastarita** [comment]
merged! gracias.
