### ISSUE TITLE
Error: connect EONNREFUSED 194.68.40.99:443

### ISSUE THREAD

**Issue by JayaSuryaTeja** [emilioastarita/lyricfier#24]
It seems like a great app, but i am not able to use it since its always giving me an error
Error details - Current song error: Error: connect EONNREFUSED 194.68.40.99:443 port is always 443

**Comment by afdalwahyu** [comment]
i have sam problem, but it fixed when i open this app with sudo command(linux) or run as administrator if you are using windows

**Comment by JayaSuryaTeja** [comment]
It doesn't seem to be the problem for me. My computer works behind a proxy, can that be the problem.

**Comment by BenjaVR** [comment]
is this issue fixed?
