### ISSUE TITLE
Wikia Search errors not caught

### ISSUE THREAD

**Issue by mrkmndz** [emilioastarita/lyricfier#28]
<img width="444" alt="screen shot 2016-12-09 at 3 18 03 am" src="https://cloud.githubusercontent.com/assets/8747216/21042239/343b7426-bdbe-11e6-9768-84a92d3376e4.png">
 With some weird non-existent songs parsing can fail.  This should not crash the app.

**Comment by emilioastarita** [comment]
Merged
