### ISSUE TITLE
HI , HOW CAN I RUN AND INSTALL ON A MAC COMPUTER

### ISSUE THREAD

**Issue by Pancho111** [emilioastarita/lyricfier#3]
hi, 
Can i run it on a Mac computer?
if yes how can I do it ?
thanks

**Comment by silvestreh** [comment]
Hey @calixto111. You can [download the Mac version](https://github.com/emilioastarita/lyricfier/releases/download/0.1.0/lyricfier-mas-x64.zip) from the [Releases page](https://github.com/emilioastarita/lyricfier/releases/tag/0.1.0) – Yeah we misspelled the platform name 😅

**Comment by Pancho111** [comment]
Very good ,thank you so much .
Do you think you can add a save or copy button  so I can embed on my files ?
once again , thank you for your hard work and fast response

**Comment by silvestreh** [comment]
You mean to have a method to store your own lyrics? Something like… I dunno… dragging a text file when a Lyric is wrong or missing? And then use your version whenever you listen to that particular song.

**Comment by silvestreh** [comment]
@emilioastarita is this something we could do? maybe store the TXT files somewhere along with the song metadata and try fetching local lyrics before hitting a third party API.

**Comment by emilioastarita** [comment]
@silvestreh yes. I think that the best thing is to add a Save Button. When you click you are saving a copy of the lyric that you could edit/modify after that. Then we add another search plugin with higher priority than the others that lookups the local database. what do u think?

**Comment by Pancho111** [comment]
Yes, to add a save button that may be can store the txt files somewhere along with the song metadata ... another thing is some songs are missing part of the lyrics or lyrics are wrong ... maybe it could be better to use musixmach ... I don't know just giving an idea.

thank you very much for your hard work
