### ISSUE TITLE
Add link to real source of the lyrics

### ISSUE THREAD

**Issue by emilioastarita** [emilioastarita/lyricfier#35]
Would be nice to add a link to the source of the lyrics to be open in the default browser.

The link must have name of the source (Wikia, MusicMatch, etc) and point directly to the lyric on their site.

**Comment by mrkmndz** [comment]
I'll give this a try right now

**Comment by mrkmndz** [comment]
Done within a big refactor

**Comment by emilioastarita** [comment]
Hey @mrkmndz your refactor it's not fully merged but I've used part of the code. If you want we can discuss how we can add your refactor in hangout! I'm closing this.
