### ISSUE TITLE
Some new feature suggestions

### ISSUE THREAD

**Issue by emredagli** [emilioastarita/lyricfier#37]
Hello,
I am a computer engineer working as mainly front-end web developer.
I found this tool on searching how can I improve my english by listening my favorite musics.
So I suggest this 2 more features:
1) On right side adding native language translations (by using google translations or some other machine translators)
2) Highlighting the lyric position of current music.
I have some ideas for that.
Thanks for your efforts. 
Kind regards,
Emre

**Comment by emilioastarita** [comment]
1) could be possible.
2) We don't know any api to get lyrics/timing metadata. What are your ideas?

**Comment by nexxio** [comment]
I have an idea for the highlighting of the lyric. 
in the beginning the spotify plugin of musicmatch let you synchronize the lyrics manually, and the synchronized lyrics data done by yourself, went to their servers so wherever that song is played the synchronization you did will be used. my idea is basically to do the same. make a manual synchronization tool, sync the lyrics and save that data in a lyricfier database. with a lyricfier user community in a short time there can be a big collection of lyrics sync data.
I was thinking about an automated way to do the same but for that you need to analyze the song audio channels or it's metadata, that I think spotify doesn't allow.

sorry for my bad english :) , and thanks for the great work you are doing.

**Comment by mrkmndz** [comment]
The issue with that is that we'd have to have a whole server/storage solution, one that would cost money to support in the long term.

**Comment by nexxio** [comment]
you are right. 
and what about a p2p network? where every lyricfier user will have the lyrics sync data in a file, the ones that it has manually synchronizated and the ones that have downloaded from another lyricfier user. it's something like a torrent. this way the collection of lyrics sync data would be distributed in all the users, and it would not need a server for storage. if you play a song lyricfier would search internet for the lyrics and search in the lyricfier network of users for the lyrics sync data.

**Comment by giu-lia** [comment]
you can make an automatic scroll for the lyrics based on the percentage of the music.. something like that :smile: it would already be very helpful!

making a button to hide the album cover/title (the header) would also be nice, would able us to let the application's window very small, displaying only the current lyrics.

anyway, thank you very much for the project!

**Comment by ailee97** [comment]
Sorry to bring up old conversation but I would highly recommend maybe working together with creator of
https://github.com/fr31/spotifylyrics/releases
I personally thinking, lyricfier has good gui settings feature, always on top, clean look and working fine
spotifylyrics is using multiple api to source lyrics and also sourcing lyrics with timing

I think together they can be one complete lyrics package to completely REPLACE old spotify lyrics feature
