### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Seeryn** [emilioastarita/lyricfier#4]
Hi, not sure if there's an option for the following or a workaround:
- Change colors to be inverted, black background and white text (similar colors to spotify client would give a more immersive experience and easier on the eyes in my opinion).
- Disable notifications. As it is now, i'm getting a notification from spotify and another from lyricfier every time spotify's song changes (Running on Linux with dunst as notification daemon).
- Move scroll bar to the top when song changes.

Otherwise really loving it, good job. Out of curiosity, what lyrics api are you using?

**Comment by silvestreh** [comment]
Those sound like good additions. We have [plugins](https://github.com/emilioastarita/lyricfier/tree/master/render/plugins) for Musixmatch and Wikia.

**Comment by emilioastarita** [comment]
@silvestreh pushed fixes for 2 and 3. Could you do 1?

**Comment by stwrtrio** [comment]
could you guys make an option for transparent background and stay on top in front any apps?
this would be a great app :)

**Comment by mauron85** [comment]
Great job. I would add "show live lyrics - karaoke".
