### ISSUE TITLE
Latin extended font subset

### ISSUE THREAD

**Issue by Laruxo** [emilioastarita/lyricfier#44]
First of all, let me thank you for an amazing plugin.

I am Lithuanian and my language has some additional characters that needs latin-extended subset to be included. Roboto font supports this subset ([https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i&amp;subset=latin-ext](url)). If this subset is not included I see very bad looking lyrics for Lithuanian songs:
![image](https://cloud.githubusercontent.com/assets/6096645/21134143/145c03de-c14f-11e6-96a8-2fcd46226ef0.png)

Also I suggest you to include cyrilic and other subsets, because you can find songs of all languages in Spotify.

**Comment by emilioastarita** [comment]
I think that we can change to
https://www.google.com/get/noto/

That could work for you?

**Comment by Laruxo** [comment]
Yes, Noto Sans support my language as well as many others.

**Comment by emilioastarita** [comment]
Hello Laruxo
I've changed the font on master branch. Could you please confirm that works for you?  

thanks!

**Comment by Laruxo** [comment]
Thank you, it looks much better.

Off topic: after I turned on Lyricfier, it loaded lyrics of the currently playing song and I switched the song I kept getting "Current song error: Error: ESOCKETTIMEDOUT" error. Probably I just did something wrong when building it, but it doesn't hurt to mention this.

**Comment by emilioastarita** [comment]
I will close this. If the new error persist on master please open a new issue with more details (song, system operative etc)
