### ISSUE TITLE
Bug double quotations marks

### ISSUE THREAD

**Issue by Seeryn** [emilioastarita/lyricfier#5]
Found a bug when lyrics contains double quotations marks (") , lyricfier shows a \ char before the quotations marks and nothing else after that. Simple quotation marks (') is parsed properly. The use of double quotation marks seems to be particular of musicxmatch, see example: https://www.musixmatch.com/lyrics/twenty-one-pilots/Holding-On-To-You

**Comment by emilioastarita** [comment]
Thanks for reporting this @Eizen. I pushed a fix for this with a better parser for MusicMatch. You could get the fix updating your repository clone or wait the next release if you are using the binaries.
