### ISSUE TITLE
Unrecognized Spotify

### ISSUE THREAD

**Issue by jsolisu** [emilioastarita/lyricfier#50]
Spofity not recognized until you push **try again** button.

![image](https://cloud.githubusercontent.com/assets/3818673/21468339/bb7724f2-c9d1-11e6-81a0-5ef585f0e16a.png)

Spotify version: 1.0.45.186.g3b5036d6
Windows version: 10.0.14393

**Comment by BenjaVR** [comment]
Can you verify that it still doesn't load if you wait longer then your 'Lyric refetch rate' setting?

**Comment by jsolisu** [comment]
Yes, If I wait longer than refresh rate it works. 

Maybe a message like "Detecting Spotify..." is convenient.

**Comment by emilioastarita** [comment]
thx for reporting.  Can you do a pull on master and try the last version. If it works for you please comment. Thanks.

**Comment by emilioastarita** [comment]
@jsolisu I'm closing this (I've already changed the message) if you see any problem in lastest release ask for reopenning the issue.
