### ISSUE TITLE
Wrong "Sorry, couldn't find lyrics for this song!" message, but can't know the real problem

### ISSUE THREAD

**Issue by eLBati** [emilioastarita/lyricfier#60]
It seems that , when fast skipping to next song, lyricfier can't correctly retrieve the lyrics.
See the screenshot

![lyri](https://cloud.githubusercontent.com/assets/1033131/22181155/caa97d7e-e085-11e6-9cee-9cff231de982.png)

I quickly skipped 2 songs and got it.

The message is clearly wrong. lyricfier should at least show the real problem (better if it correctly retrieved lyrics :smirk:)

**Comment by wacevedo** [comment]
Hi, Im getting this problem with all the songs. 😐

**Comment by MythodeaLoL** [comment]
Same problem here. :face_with_head_bandage:

**Comment by patolinlp** [comment]
Same problem :(

**Comment by azelos** [comment]
Same problem here. Any solution for this??

![image](https://cloud.githubusercontent.com/assets/25454240/22461101/99e33676-e7b0-11e6-94da-c6d0ac864a87.png)

**Comment by wacevedo** [comment]
If you know what is causing this problem maybe I can check it and try something, any thoughts?

**Comment by KrisCvetkovikj** [comment]
I believe it's failing on https://github.com/emilioastarita/lyricfier/blob/master/render/SongRender.ts#L76

From what I can see, the library (plugin) isn't that good, maybe I could do a pull request with a different one this weekend.

**Comment by wacevedo** [comment]
@k1ko If there is anything I can help let me know.

**Comment by andersmogensen** [comment]
Same problem, finds the correct song, but cant find lyrics.

**Comment by PeterMX** [comment]
same problem, fix it fast please! 
![captura de pantalla de 2017-02-01 22-52-00](https://cloud.githubusercontent.com/assets/9899682/22537545/1b0971c2-e8d1-11e6-9ce2-0bfb81a4d3c3.png)

**Comment by PolluxDK** [comment]
Same issue here, unable to load lyrics for all songs. On different pc's.
Win10

**Comment by MythodeaLoL** [comment]
i'm using this as alternative, seems **better**.
https://www.microsoft.com/en-us/store/p/musixmatch-desktop/9wzdncrfj235

![alt tag](https://store-images.s-microsoft.com/image/apps.30444.9007199266242800.1f3ff047-ce77-4ae9-a745-5fcef4b16c67.ec050b57-b907-4025-bf00-df2b08502ff9?w=1399&h=787&q=60)

**R.I.P. lyricfier.**

**Comment by KrisCvetkovikj** [comment]
Go away, mate.

**Comment by SamuelNeves** [comment]
Its back!!=D Thanks

**Comment by linuxdood** [comment]
I am getting same thing... it worked 2 weeks ago and then just stopped one day.
I am running a standard ubuntu 16.10 install on an Intel NUC and Spotify Premium.
I poked around the dev tools and I does not appear to be getting the information from Spotify to do the search... but not sure.
I will also try this on a laptop here and see if I get same result.
![selection_004](https://cloud.githubusercontent.com/assets/25709654/23867594/c30673a8-07f2-11e7-8e21-574ce59fd1f9.png)

This is a terrific app.... HELP!

**Comment by erwinlagu** [comment]
Fixed
