### ISSUE TITLE
"Sorry, couldn't find lyrics for this song!" on every song

### ISSUE THREAD

**Issue by akappen** [emilioastarita/lyricfier#64]
Lyrics have not been loading for any songs for the last several days. Since the app worked before I figured it must be due to a change in one of the lyrics providers.

I removed each search plugin and identified the MusicMatch plugin as the problem. With that plugin removed lyrics loaded correctly again.

I think a lot of people (probably all of them) are having this problem, Issue #60 is where people are reporting this bug although the description in that Issue is not correct.

Thank you so much for this plugin! It is great and when it stopped working I HAD to figure out a workaround.

**Comment by mrsmartuchi** [comment]
Same problem in my case.....

**Comment by RobFog** [comment]
Ditto.

**Comment by MythodeaLoL** [comment]
see
https://github.com/emilioastarita/lyricfier/issues/60#issuecomment-277493863

**Comment by RobFog** [comment]
Issue's gone for me. :-)

**Comment by moeinrahimi** [comment]
i have same problem here

**Comment by JostCrow** [comment]
For me at the new version the error is still there. (Ubuntu)
```
Error getting csrf token URL: http://127.0.0.1:4371/simplecsrf/token.json
```
This is what the getStatus is logging:
```
client_version: "1.0.49.125.g72ee7853"
error: Object
  message: "Invalid OAuth token"
  type: "4102"
running: true
version: 9
```

**Comment by emilioastarita** [comment]
check last release please.
