### ISSUE TITLE
Current song error: No song / "Invalid OAuth token"

### ISSUE THREAD

**Issue by uszasty** [emilioastarita/lyricfier#69]
I made sure that all spotify domains are unlocked in hosts. In app it shows "Current song error: No song" and in developer console every time this happens this shows up:
`Object {error: Object, version: 9, client_version: "1.0.50.41368.gbd68dbef", running: true}
client_version:"1.0.50.41368.gbd68dbef"
error:Object
message:"Invalid OAuth token"
type:"4102"
__proto__:Object
running:true
version:9
__proto__:Object`

I've already tried reunzipping archive and relogging in Spotify

**Comment by WuTofu** [comment]
i found something, hope this would help developer(s).

https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/135
