### ISSUE TITLE
Current song error: No song

### ISSUE THREAD

**Issue by randyraharjo93** [emilioastarita/lyricfier#71]
I would really love to use this app.

I just download from https://github.com/emilioastarita/lyricfier/releases Linux x-64 edition

Opened the lyricfier, open the executable. And bam, the title says it all.

Am I doing something wrong? Please tell me a clue.

**Comment by MythodeaLoL** [comment]
same problem, the Fix dont work.

**Comment by randyraharjo93** [comment]
@FloridaStream Actually The fix work. Just need to apply the code in the release version.

Or if you prefer, 

[mol_lyricfier.zip](https://github.com/emilioastarita/lyricfier/files/852262/mol_lyricfier.zip)

Replace lyricfier original file with my file in *yourlyricfierfolder*/resources/app/render/

Hope it works. Cheers.

**Comment by madaaah** [comment]
Hey! Great app, loving the intention and the interface...

I had the No songs problem and applied this fix, now it recognizes the song being played, but the lyrics still don't show... No error message. I'm on mac, not sure if that's the reason.

Thank you, guys!

**Comment by martinstingl** [comment]
The fix works! Thank you.

**Comment by Thomastasa** [comment]
Thank you @randyraharjo93 :) that fix worked for me too (windows 10)

**Comment by octoberinthesky** [comment]
It worked for me (window 10), but the same problem appeared again days ago after I updated my spotify, would you please make some adjustments for the new version? Thank you :)

**Comment by CharlotteCharlotte** [comment]
@randyraharjo93  Thanks!! Now I haven't any problem with the app on Windows10. Thanks for your time!

**Comment by randyraharjo93** [comment]
@octoberinthesky Unfortunately, We must wait for lyricfier team to fix that. :(

**Comment by stixbunny** [comment]
Just tried it, it works! Thanks!

**Comment by RegiusK** [comment]
Thanks! @randyraharjo93 . Worked on ubuntu x64.

**Comment by octoberinthesky** [comment]
@randyraharjo93 Worked now! Thank you so much for replying :)

**Comment by jgarcia241** [comment]
Thanks!

**Comment by SamuelNeves** [comment]
Thanks @randyraharjo93  you save my musics xD.

**Comment by ecamana** [comment]
Perfect! It worked perfectly. Thanks @randyraharjo93

**Comment by magoz** [comment]
The fix worked for me as well (MacOS Sierra). Thanks!

**Comment by rizkyfirmansyah** [comment]
Great! It worked perfectly on my Windows 10. Thanks a bunch @randyraharjo93

**Comment by MoazzamDar** [comment]
The fix works on my Windows 10! Thank you @randyraharjo93.

**Comment by hilam** [comment]
The fix works on my Windows 10! Thank you @randyraharjo93.

**Comment by memoryonrepeat** [comment]
Perfect! Thanks @randyraharjo93

**Comment by donbzm** [comment]
[https://github.com/emilioastarita/lyricfier/issues/76](url)

**Comment by Angelwolf97** [comment]
The fix worked fine to me and I really appreciate that, but today Spotify updated and Lyricfier won't work anymore. Please help!!

**Comment by randyraharjo93** [comment]
Unfortunately, no update from lyricfier team yet.

**Comment by emilioastarita** [comment]
we can't release again that version because it has the musicmatch plugin. They did a DMCA complain against this repo :( sorry guys.

**Comment by emilioastarita** [comment]
Hello! 
Could you please try last release? and give some feedback?
https://github.com/emilioastarita/lyricfier/releases
thx!

**Comment by Angelwolf97** [comment]
Sorry, been under a Hurricane, couldn't see your message until now. I will
try the last version as soon as I can, but there is no electricity in my
town since the Hurricane Maria, so it will be in a long time. Again, sorry
for not responding earlier.
Thanks for your hard work.
