### ISSUE TITLE
Please make a new release for windows with bug fixed.

### ISSUE THREAD

**Issue by MythodeaLoL** [emilioastarita/lyricfier#73]
I tried everything, but no method solved the problem, no bug fix, nothing, please make a compiled version for windows.

**Comment by MrJerB** [comment]
Release version doesn't work but building from source does. If you've got the tooling setup, building is as simple as:

`npm run-script dist:win32`
or
`npm run-script dist:win64`

Output goes to the build folder.

**Comment by emilioastarita** [comment]
Could you please try last release?
https://github.com/emilioastarita/lyricfier/releases
thx!
