### ISSUE TITLE
STILL: Current song error: no song.

### ISSUE THREAD

**Issue by ghost** [emilioastarita/lyricfier#74]
I downloaded the most recent release, downloaded the most recent uncompiled version (which was said to fix the issue) and replaced the files in /resources/app (Windows) with those of the uncompiled version. The issue persists. The new UI looks nicer at least. Keep up the good work and let's see when I can go back to using this awesome app!

**Comment by emilioastarita** [comment]
We will fix this on next release

**Comment by randyraharjo93** [comment]
@theluckyg for impatient ppl :D  https://github.com/emilioastarita/lyricfier/issues/71

**Comment by jav-12** [comment]
Hi, When it will be fixed?

**Comment by darlanmoraes** [comment]
Still happening, --product-version=Spotify/1.0.49.125

**Comment by minarinho** [comment]
Still happening
Spotify Version = 1.0.55.487.g256699aa

**Comment by Kuki77** [comment]
Still happening. 

Win 8.1 64bit
Spotify 1.0.53.758.gde3fc4b2

**Comment by WildfootW** [comment]
Win 10 64bit
Spotify 1.0.59.395.ge6ca9946

**Comment by ascorti** [comment]
The same for me

Max OSX 10.12.6
Spotify 1.0.60.492.gbb40dab8

**Comment by jnnkls** [comment]
Also here

Win 10 64-Bit
Spotify 1.0.64.399.g4637b02a

**Comment by emilioastarita** [comment]
Could you please try last release?
https://github.com/emilioastarita/lyricfier/releases
thx!

**Comment by emilioastarita** [comment]
I'm closing this as should be solved in last release.

**Comment by rgalhama** [comment]
But yet still happening in linux... any recent fix?

**Comment by luisramirezdev** [comment]
@rgalhama Maybe this is the problem: https://github.com/emilioastarita/lyricfier/issues/103#issuecomment-407372908

**Comment by rgalhama** [comment]
Looks like it @luisramirez-m , I'll move it to this thread. Thanks!
