### ISSUE TITLE
Sorry, couldn't find lyrics for this song!

### ISSUE THREAD

**Issue by Sethior** [emilioastarita/lyricfier#76]
First I got the #71 issue. When replaced the files it worked for one or two songs and now i'm getting:

"Sorry, couldn't find lyrics for this song!" for all songs...

**Comment by AntonioWalker7** [comment]
I have the same problem. Initially, I obtained #71 issue. Then, replacing the files, this problem was solved, but a new problem appeared: every song (title and artist) is truly recognized, but it doesn't show any lyrics. "Sorry, couldn't find lyrics for this song!"

![image](https://user-images.githubusercontent.com/30079086/28072294-de392e7c-6652-11e7-8d10-43b22eca7aa5.png)

**Comment by donbzm** [comment]
Exactly the same problem here, running on Ubuntu 16.04 64

**Comment by sysads** [comment]
same issue here. Any fix yet?

**Comment by alemaltos** [comment]
I have the same problem on Windows x64 and I really miss the app :(

**Comment by fredericoraiss** [comment]
i have same problem! :(

**Comment by marcos1262** [comment]
same problem here... Linux-x64

**Comment by chmiiller** [comment]
same here - osx Sierra
Error is:
![error](https://user-images.githubusercontent.com/1013632/28309102-9940cea0-6ba8-11e7-948b-7e47205c5ae3.png)

**Comment by chmiiller** [comment]
hun, something is wrong with all the `/`
In my case the url is: 
`http://www.musixmatch.com/u002Flyrics/u002FQueensr%C3%BFche/u002FSuite-Sister-Mary-2003-Digital-Remaster`
When it should be:
`http://www.musixmatch.com/lyrics/Queensr%C3%BFche/Suite-Sister-Mary-2003-Digital-Remaster`

**Comment by thisisrachelramos** [comment]
Unicode number 0002 is the "Start of text" character, there must be an issue with the URL generated. Will have to look at the code to figure out where this is happening.
Source:  https://unicode-table.com/en/search/?q=0002

**Comment by sysads** [comment]
So any fix yet?

**Comment by memoryonrepeat** [comment]
The MusicMatch scraper no longer works, seemingly due to their [limited free plan](https://developer.musixmatch.com/plans). Author also [took down](https://github.com/emilioastarita/lyricfier/commit/d8758bcc84b3543f7844e9199cb53e056769b430) the MusicMatch dependency, but somehow the latest code is still not released yet.

So easiest way to fix this is to overwrite the search module with the latest code like what we did in #71 . Simply replace the original files in _yourlyricfierfolder/resources/app/render/_ by the ones below.

[fix_lyrics_not_found.zip](https://github.com/emilioastarita/lyricfier/files/1176862/fix_lyrics_not_found.zip)

**Comment by alemaltos** [comment]
OMG, IT WORKS!!! Thank you @tienthanh8490 !!!!
![image](https://user-images.githubusercontent.com/27831469/28627368-396ee918-71e7-11e7-928e-ab6cd43faf8c.png)

**Comment by chmiiller** [comment]
Just works!

**Comment by AntonioWalker7** [comment]
It definitely works! Thanks @tienthanh8490

**Comment by tkreque** [comment]
Thanks @tienthanh8490, worked perfectly!

**Comment by arielgiomi** [comment]
Perfect! Thanks @tienthanh8490

**Comment by gustavovelascoh** [comment]
It works, Thanks @tienthanh8490

**Comment by emilioastarita** [comment]
Could you please try last release?
https://github.com/emilioastarita/lyricfier/releases/tag/0.2.6
thx!

**Comment by memoryonrepeat** [comment]
@emilioastarita The new version crashed on first start. Seems to be compatibility issue with macOS latest version. This is the log I got.

```
Process:               lyricfier [78104]
Path:                  /Volumes/VOLUME/*/lyricfier.app/Contents/MacOS/lyricfier
Identifier:            com.electron.lyricfier
Version:               0.2.6 (0.2.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           lyricfier [78104]
User ID:               501

Date/Time:             2017-10-04 23:31:24.121 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        152DE4D8-4308-178D-E6F2-EFD343D92F89

Sleep/Wake UUID:       C57232AF-AA17-4210-A563-04A30DD59DF3

Time Awake Since Boot: 1800000 seconds
Time Since Wake:       240 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Volumes/VOLUME/*/lyricfier.app/Contents/MacOS/lyricfier
  Reason: image not found

Binary Images:
       0x103d7e000 -        0x103d7eff7 +com.electron.lyricfier (0.2.6 - 0.2.6) <107BF4A4-1BF7-306B-944D-7DED190A60FE> /var/folders/*/lyricfier.app/Contents/MacOS/lyricfier
       0x108ed9000 -        0x108f16dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld

Model: MacBookPro12,1, BootROM MBP121.0167.B33, 2 processors, Intel Core i5, 2.9 GHz, 16 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Card Reader
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

```

**Comment by emilioastarita** [comment]
@tienthanh8490 thanks for reporting. I think that the problem have to do with the build. I rebuilded with newer versions of the packager. Could you please re-download the new zip? If it fails I will try with a mac tomorrow.

**Comment by memoryonrepeat** [comment]
@emilioastarita It still fail, similar error. Let me know if anything I can help.

**Comment by emilioastarita** [comment]
@tienthanh8490 thanks for testing. Maybe could you try running `yarn install` (or npm) and then `yarn run start`. If that works also could be useful that you try produce the build yourself with `yarn run dist`. Let me know if you have any problem with this commands.

**Comment by memoryonrepeat** [comment]
@emilioastarita Just tried building with npm, it works for the first song, then when I change to another song it crashed. Seems like a v8 error ?

```
[80614:1005/012247.715625:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
0   Electron Framework                  0x000000010686f43c crashpad::CloseMultipleNowOrOnExec(int, int) + 970204
1   Electron Framework                  0x0000000106836c53 crashpad::CloseMultipleNowOrOnExec(int, int) + 738803
2   Electron Framework                  0x000000010684e6b1 crashpad::CloseMultipleNowOrOnExec(int, int) + 835665
3   Electron Framework                  0x00000001094eaa9c crashpad::CloseMultipleNowOrOnExec(int, int) + 47612988
4   libnode.dylib                       0x000000010af23021 v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 19633
5   libnode.dylib                       0x000000010b3ad179 v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 21993
6   libnode.dylib                       0x000000010b3bb2d0 v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 79680
7   libnode.dylib                       0x000000010b3adf70 v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 25568
8   libnode.dylib                       0x000000010b3a6717 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 73127
9   libnode.dylib                       0x000000010b3a430e v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 63902
10  libnode.dylib                       0x000000010b1c1aa3 v8::internal::Heap::CreateFillerObjectAt(unsigned char*, int, v8::internal::ClearRecordedSlots) + 7555
11  libnode.dylib                       0x000000010b1c02d5 v8::internal::Heap::CreateFillerObjectAt(unsigned char*, int, v8::internal::ClearRecordedSlots) + 1461
12  libnode.dylib                       0x000000010b1bf813 v8::internal::DeferredHandleScope::Detach() + 110595
13  libnode.dylib                       0x000000010b1ce7be v8::internal::Heap::CreateFillerObjectAt(unsigned char*, int, v8::internal::ClearRecordedSlots) + 60062
14  libnode.dylib                       0x000000010b26cec6 v8::internal::IdentityMapBase::NextIndex(int) const + 950
15  Electron Framework                  0x000000010687ffc1 crashpad::CloseMultipleNowOrOnExec(int, int) + 1038689
16  Electron Framework                  0x000000010948c07f crashpad::CloseMultipleNowOrOnExec(int, int) + 47225375
17  Electron Framework                  0x000000010948a0d2 crashpad::CloseMultipleNowOrOnExec(int, int) + 47217266
18  Electron Framework                  0x000000010687ffc1 crashpad::CloseMultipleNowOrOnExec(int, int) + 1038689
19  Electron Framework                  0x000000010684837b crashpad::CloseMultipleNowOrOnExec(int, int) + 810267
20  Electron Framework                  0x00000001068486cc crashpad::CloseMultipleNowOrOnExec(int, int) + 811116
21  Electron Framework                  0x0000000106848a83 crashpad::CloseMultipleNowOrOnExec(int, int) + 812067
22  Electron Framework                  0x000000010684bf0a crashpad::CloseMultipleNowOrOnExec(int, int) + 825514
23  Electron Framework                  0x00000001067fb0ca crashpad::CloseMultipleNowOrOnExec(int, int) + 494186
24  Electron Framework                  0x000000010684b92f crashpad::CloseMultipleNowOrOnExec(int, int) + 824015
25  CoreFoundation                      0x00007fff81415321 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26  CoreFoundation                      0x00007fff813f621d __CFRunLoopDoSources0 + 557
27  CoreFoundation                      0x00007fff813f5716 __CFRunLoopRun + 934
28  CoreFoundation                      0x00007fff813f5114 CFRunLoopRunSpecific + 420
29  Foundation                          0x00007fff82e08252 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30  Electron Framework                  0x000000010684c5ae crashpad::CloseMultipleNowOrOnExec(int, int) + 827214
31  Electron Framework                  0x000000010684bd6c crashpad::CloseMultipleNowOrOnExec(int, int) + 825100
32  Electron Framework                  0x000000010684804e crashpad::CloseMultipleNowOrOnExec(int, int) + 809454
33  Electron Framework                  0x0000000106861183 crashpad::CloseMultipleNowOrOnExec(int, int) + 912163
34  Electron Framework                  0x00000001071b0c1c crashpad::CloseMultipleNowOrOnExec(int, int) + 10675644
35  Electron Framework                  0x0000000106a1d68b crashpad::CloseMultipleNowOrOnExec(int, int) + 2732075
36  Electron Framework                  0x00000001084dee18 crashpad::CloseMultipleNowOrOnExec(int, int) + 30787512
37  Electron Framework                  0x0000000106a1c8e4 crashpad::CloseMultipleNowOrOnExec(int, int) + 2728580
38  Electron Framework                  0x00000001065fa90a AtomMain + 74
39  Electron Helper                     0x00000001065f1f26 main + 38
40  libdyld.dylib                       0x00007fff96b75235 start + 1
41  ???                                 0x0000000000000011 0x0 + 17
```

**Comment by emilioastarita** [comment]
Yes it seems a problem with the v8 bundled in electron (1.8.1). I downgraded to 1.7.8. Could you try again with last commit:
```
git pull
npm install
npm run start
```

**Comment by memoryonrepeat** [comment]
@emilioastarita Yea 1.7.8 seems to be more stable - it stopped crashing. 
Just a minor issue - when I switch to an instrumental song (no lyric found), there is an uncaught exception

```
Uncaught TypeError: Cannot read property 'lyric' of null
    at searcher.search (/Users/thanhnguyen/lyricfier/render/SongRender.js:60:31)
    at async.parallel (/Users/thanhnguyen/lyricfier/render/Searcher.js:41:17)
    at /Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:3861:9
    at /Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:998:13)
    at /Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:906:16
    at /Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:3858:13
    at callback (/Users/thanhnguyen/lyricfier/node_modules/async/dist/async.js:4261:17)
    at plugin.search (/Users/thanhnguyen/lyricfier/render/Searcher.js:26:32)
    at Request.doReq [as _callback] (/Users/thanhnguyen/lyricfier/render/plugins/Genius.js:28:17)
```

**Comment by emilioastarita** [comment]
Thanks i've fixed that. I will prepare another release soon

**Comment by emilioastarita** [comment]
@tienthanh8490 when you have some time could you please try the mac new release ? thx!

**Comment by fjpalacios** [comment]
Hi, the new Mac version is crashing too. I provide you the log:

Process:               lyricfier [15203]
Path:                  /private/var/folders/*/lyricfier.app/Contents/MacOS/lyricfier
Identifier:            com.electron.lyricfier
Version:               0.2.7 (0.2.7)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           lyricfier [15203]
User ID:               501

Date/Time:             2017-10-04 23:57:54.081 +0200
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        EF446C4F-6390-F4D1-A728-B7372929CAE8


Time Awake Since Boot: 31000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/lyricfier.app/Contents/MacOS/lyricfier
  Reason: image not found

Binary Images:
       0x1046cf000 -        0x1046cfff7 +com.electron.lyricfier (0.2.7 - 0.2.7) <107BF4A4-1BF7-306B-944D-7DED190A60FE> /var/folders/*/lyricfier.app/Contents/MacOS/lyricfier
       0x10de79000 -        0x10deb6dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld

**Comment by emilioastarita** [comment]
@fjpalacios thanks for reporting. I've uploaded a new version. Could you please try this one? Sorry but I don't have a mac to test before releasing. Thanks!

**Comment by Sethior** [comment]
Hi. This version is now working for me on Windows 10. Thank you so much :)

**Comment by memoryonrepeat** [comment]
@emilioastarita Just tested, latest version seems stable enough for release. Thanks! (Y)

**Comment by fjpalacios** [comment]
@emilioastarita yep, latest release works like a charm for me too. Thanks!

**Comment by emilioastarita** [comment]
thanks to all testers! I'm closing this issue.
