### ISSUE TITLE
Sorry not issue new website for me thanks 

### ISSUE THREAD

**Issue by ailee97** [emilioastarita/lyricfier#77]
I would highly recommend maybe working together with creator of
https://github.com/fr31/spotifylyrics/releases
I personally thinking, lyricfier has good gui settings feature, always on top, clean look and working fine
spotifylyrics is using multiple api to source lyrics and also sourcing lyrics with timing

I think together they can be one complete lyrics package to completely REPLACE old spotify lyrics feature

sorry i dont know how to contact direct

**Comment by emilioastarita** [comment]
sorry this are different projects.
