### ISSUE TITLE
Current song error: Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by alemaltos** [emilioastarita/lyricfier#78]
Hi, 

I`m new here, a minute ago I created the account just to share the following issue, so I dont know how this works exactly.

Yesterday my Spotify application was updated and today I get the following error in lyricfier
Current song error: Error: ESOCKETTIMEDOUT

Today I downloaded the latest update for Windows 64 bit again but the error continues.

PS. Thanks for create Lyricfier, I love this great app <3

**Comment by goSOSog** [comment]
I have the Same problem.
It says also: "Current song error: No song"
I downloaded this program a few minutes ago, so I don't know how it work. When I try to drag the current song into lyricfier, it want me to login. But there I cant login with Facebook.

**Comment by zaoky** [comment]
+1 I downloaded a few minutes ago too and I am getting this error
Current song error: Error: ESOCKETTIMEDOUT

maybe I am skipping something!!

**Comment by serra-pablo** [comment]
Great app. I also got 'Current song error: No song'. After some probing (that I can't recreate) it gave the error: 'Error: ESOCKETTIMEDOUT'

**Comment by alemaltos** [comment]
Actually I found the solution on #71 , just donwload the zip and follow the instructions.

**Comment by dhgdanzmodz** [comment]
its not working for me :( ive tried the #71 fix it did nothing

**Comment by emilioastarita** [comment]
Could you please try last release?
https://github.com/emilioastarita/lyricfier/releases/tag/0.2.6
thx!
