### ISSUE TITLE
Help me I dont know what im doing

### ISSUE THREAD

**Issue by serikbol** [emilioastarita/lyricfier#8]
Hi how do I use this. I'm not too smart with computers just wanna listen to music

**Comment by silvestreh** [comment]
Hi @serikbol … this is an app that displays lyrics for whatever song you're currently listening on Spotify. That being said, you should [download](https://www.spotify.com/download) and install Spotify first.

Once that's done you can download Lyricfier from the [releases section](https://github.com/emilioastarita/lyricfier/releases). Unless you're rocking some old hardware, you probably want the `x64` version for your platform (Windows, Linux, or Mac)

**Comment by emilioastarita** [comment]
Maybe the issue here is a better readme and nicer download buttons for each plattform? @silvestreh ?

**Comment by serikbol** [comment]
Thanks I've gotten that far but are the lyrics supposed to show up when I
play music? Because they're not showing up

**Comment by emilioastarita** [comment]
Yes. If you have spotify and lyricfier open, lyricfier it's supposed to show the lyric of the current song.

Could you provide the message that you see at the bottom box of the lyricfier app when you change the song ? Do you see any error or anything?

**Comment by endrureza** [comment]
open spotify 
open lyricfier
play a song
take a look at lyricfier, should show lyric actually

that's all

**Comment by serikbol** [comment]
Hope do I open lyricfier because I only see vlc files and other stuff

**Comment by serikbol** [comment]
K realised I was being stupid so thanks and sorry for letting me waste your
time

**Comment by serikbol** [comment]
What should I open the files with?

**Comment by silvestreh** [comment]
@serikbol Lyricfier doesn't open any type of file. What it does is find lyrics for whatever song you're currently listening on Spotify and **only** Spotify.
