### ISSUE TITLE
 async.detectSeries or async.eachSeries

### ISSUE THREAD

**Issue by juelvaldivia** [emilioastarita/lyricfier#80]
I installed Llyricfier but always I see the next legend "Sorry, couldn't find lyrics for this song!"

I saw the code in Searcher.ts  method "search" and I changed  "async.detectSeries" for "async.eachSeries"

Now recognize the Wikia plugin, but it don't recognize others plugins

**Comment by memoryonrepeat** [comment]
You may want to try [this](https://github.com/emilioastarita/lyricfier/issues/76#issuecomment-318067858)

**Comment by emilioastarita** [comment]
hi! could you please test the last release? 
https://github.com/emilioastarita/lyricfier/releases/tag/0.2.6
