### ISSUE TITLE
Lyrics sync

### ISSUE THREAD

**Issue by BenjaVR** [emilioastarita/lyricfier#85]
A nice feature would be to sync lyrics with the songs.
Some thoughts about this:
- There should be a database to store the syncing data
- We could store the lyrics there as well
- Note for previous point: what about lyric copyrights? We can't scrape lyrics and store them I suppose. Maybe manual contributions from users (and only make those lyrics 'syncable')? Anyone some knowledge about what is legal?
- Accept donations to be sure the servers are paid (or a small one-time payments for the sync feature?)

Just some thoughts, please say what you guys think about this!

**Comment by emilioastarita** [comment]
Is out of the scope for this project to have  server storing user's songs. A good alternative could be to store the lyrics as txt files on clients. That way you can export / import the lyrics or use Dropbox/Drive sync features. If you are interested in this feature please open another issue describing that.
