### ISSUE TITLE
Bug: Genius Scraper sometimes yields top hits instead of lyrics

### ISSUE THREAD

**Issue by pandeykartikey** [emilioastarita/lyricfier#88]
![screenshot from 2017-11-06 06-21-51](https://user-images.githubusercontent.com/24077854/32421100-c8c6f348-c2ba-11e7-9df4-1768b91a8294.png)

**Comment by Acen** [comment]
This is fixed by #89. Can it be closed?

**Comment by emilioastarita** [comment]
yes!
