### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by luill** [emilioastarita/lyricfier#9]
Hey Guys!

I'm here just to say how much I'm thank full for your guys taking your free time to do this program.

The internet is better with people like you. 

THANK YOU SO MUCH!

And sucess to you all in all of your projects.

best regards.

**Comment by kugrjado** [comment]
I was about to post similiar post :)

I'm glad someone was so motivated to start a project like this!
THANK YOU! <3

And the fact it's beeing made for three OS platforms... Simply WOW!

**Comment by emilioastarita** [comment]
Thanks!
